name: Stats (full)

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  logs:
    name: Compute full logs
    runs-on: ubuntu-latest
    env:
      TOOLS_STORAGE_ACCESS_KEY: ${{ secrets.TOOLS_STORAGE_ACCESS_KEY }}
      TOOLS_STORAGE_SECRET_KEY: ${{ secrets.TOOLS_STORAGE_SECRET_KEY }}
      LOG_BUCKET: ${{ secrets.LOG_BUCKET }}
      LOG_DB_BUCKET: ${{ secrets.LOG_DB_BUCKET }}
      STATS_BUCKET: ${{ secrets.STATS_BUCKET }}
      MMDB_TOKEN: ${{ secrets.MMDB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v1
      - name: compute full logs
        run: make config stats-full
      - name: backup stats
        run: make stats-catalog stats-db-backup stats-backup
      - name: 📰 slack notification
        run: |
          APPARIEMENTS=$(ls stats/public/`date +%Y`S* | tail -n 1 | xargs cat | jq '[.[keys[] | select(contains("api: search/csv GET"))]] | .[0] | .requests.data | .[0] | .bytes.count' | awk ' {print $1/400}')
          make -C tools slack-notification SLACK_MSG="nombre appariements cette semaine ${APPARIEMENTS}" SLACK_TITLE="Stats - deces.matchid.io" SLACK_WEBHOOK="$SLACK_WEBHOOK"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
