name: pull request

on: pull_request

jobs:
  test:
    name: Pull request test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF} | sed 's|^refs/heads/||;' | sed 's/[^a-zA-Z0-9]/-/g')"
        id: extract_branch
      - name: config
        run: make version config
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: build
        if: success()
        run: make docker-check || make build
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: test
        if: success()
        run: |
          make deploy-local backend-test
        env:
          FILES_TO_PROCESS: deces-2020-m01.txt.gz
          REPOSITORY_BUCKET: fichier-des-personnes-decedees-elasticsearch-dev
          API_SEARCH_LIMIT_RATE: 10r/s
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          STORAGE_SECRET_KEY: ${{ secrets.STORAGE_SECRET_KEY }}
          TOOLS_STORAGE_ACCESS_KEY: ${{ secrets.TOOLS_STORAGE_ACCESS_KEY }}
          TOOLS_STORAGE_SECRET_KEY: ${{ secrets.TOOLS_STORAGE_SECRET_KEY }}
          LOG_BUCKET: ${{ secrets.LOG_BUCKET }}
          LOG_DB_BUCKET: ${{ secrets.LOG_DB_BUCKET }}
          STATS_BUCKET: ${{ secrets.STATS_BUCKET }}
          PROOFS_BUCKET: ${{ secrets.PROOFS_BUCKET }}
          BACKEND_TOKEN_KEY: ${{ secrets.BACKEND_TOKEN_KEY }}
          BACKEND_TOKEN_PASSWORD: ${{ secrets.BACKEND_TOKEN_PASSWORD }}
