name: PR build and test

on: pull_request

jobs:
  build:
    name: build test and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: config
        run: make config
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: build
        run: make docker-check || make build
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: local test
        if: ${{ success() }}
        run: deploy-local
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          FILES_TO_PROCESS: deces-2020-m01.txt.gz
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
          STORAGE_SECRET_KEY: ${{ secrets.STORAGE_SECRET_KEY }}
